version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
